### ISSUE TITLE
Add horizontal angle

### ISSUE THREAD

**Issue by jeffmckee** [dreo-team/hass-dreoverse#31]
### Checklist

- [x] I have filled out the template to the best of my ability.
- [x] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [x] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

The number one reason why I purchased a Dreo fan (DR-HPF005S) instead of another smart fan was the ability to adjust the horizontal angle so that I could have the fan adjust to a few preset spots in the room without needing to manually adjust. 

### Describe the solution you'd like

Please expose horizontal angle as a number entity in Home assistant OR fix the DR-HPF005S API

### Describe alternatives you've considered

The oscillate toggle sort of is a workaround but it's really annoying because if there's a lag in the toggle being registered you have to completely wait for it to do a full loop. 

### Additional context

This functionality exists in @JeffSteinbok integration for other models but not DR-HPF005S, because the API for that device is different for some reason, see: https://github.com/JeffSteinbok/hass-dreo/issues/339. If you could just fix the API that would solve the issue, or use a different API for this model to adjust hangleadj

**Comment by dreo-team** [comment]
Thanks for the request and detailed background. At the moment, Home Assistant’s built‑in entities don’t natively cover precise horizontal angle control for this model. We’re actively designing a more complete angle-control component to expose this as a proper number entity and integrate with the DR‑HPF005S API. It’s on our roadmap—stay tuned!

**Comment by alvst** [comment]
Seconding the request for this to be added to the API. I was looking for this capability this weekend for a project I'm working on which, without the angle, isn't possible (or at the very least is very unreliable. Additionally, the ability to send the fan a request to turn to X degrees would be much appreciated.

**Comment by innocenzi** [comment]
Hey, I migrated from Jeff's integration to this one, since https://github.com/dreo-team/hass-dreoverse/issues/29 was fixed. I have the `DR-HPF002S` and I miss that feature now that I have migrated.

**Comment by GLT013** [comment]
> Hey, I migrated from Jeff's integration to this one, since [#29](https://github.com/dreo-team/hass-dreoverse/issues/29) was fixed. I have the `DR-HPF002S` and I miss that feature now that I have migrated.

Same here. Hopefully its coming soon.

**Comment by JeffSteinbok** [comment]
@dreo-team  what do you think about collaborating?

**Comment by monstermuffin** [comment]
Bumping this, horizontal angle adjustment should be looked into as it's a core function that is still not available.
